### ISSUE TITLE
How to prepare input data of scans ? 

### ISSUE THREAD

**Issue by issibi** [sergeyprokudin/bps#3]
I get point cloud data out of  my scanner.

when testing bps i could not manage to feed in files as point cloud.
ERROR: 
if hasattr(scan, 'colors') and (scan.colors[0] is not None):
IndexError: index 0 is out of bounds for axis 0 with size 0

It worked well if i converted the point cloud to a triangle mesh. 

is there any way to use point cloud data directly or do i have to convert first to a mesh ?
i am using open3d.

Thumbs up! Great work!
BPS worked for me out of the box with one little problem:
KeyError: '3d'

This can be solved with this line in run_alignment.py
from mpl_toolkits.mplot3d import Axes3D # <--- This is important for 3d plotting 
https://stackoverflow.com/questions/56222259/valueerror-unknown-projection-3d-once-again
(Maybe some problem with my matplotlib version)

**Comment by sergeyprokudin** [comment]
Hi issibi,

thanks for your interest!

Regarding this:

>  IndexError: index 0 is out of bounds for axis 0 with size 0

First of all, does your scan have RGB colors?

If so, the problem is that the color channel loaded by trimesh is somehow different from what is expected by the alignment script. Can you check what is the output of

```
scan = trimesh.load_mesh(your_scan_path)
print(type(scan.colors))
print(scan.colors.shape)
```

for your scan?

In any case, I've added generic handling of this exception for now: if for some reason color loading have issues, it will use the default green colouring for visualisation (the colors are only used for this really and not for the alignment itself).

> from mpl_toolkits.mplot3d import Axes3D # <--- This is important for 3d plotting

fixed, thanks!

**Comment by issibi** [comment]
Thnx for fast reply.

Output of the script was:

Type Colors:  <class 'trimesh.caching.TrackedArray'>
Shape:  (0,)

Then i  painted the Point Cloud with some uniform color, now the output is:

Type Colors:  <class 'trimesh.caching.TrackedArray'>
Shape:  (45896, 4)

But now i get a different error in run_alignment.py:

% python run_alignment.py scan_for_test.ply ../logs/demo_output
processing scan_for_test.ply
loading and denoising scan..
Traceback (most recent call last):
  File "run_alignment.py", line 209, in <module>
    main()
  File "run_alignment.py", line 196, in main
    process_scan(scan_path, CKPT_PATH, out_dir)
  File "run_alignment.py", line 166, in process_scan
    x_orig, x_proc = load_scan(scan_path)
  File "run_alignment.py", line 62, in load_scan
    scan_orig = np.concatenate([np.asarray(scan.vertices), scan_rgb], 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


For info the header of my point current cloud:

ply
format binary_little_endian 1.0
comment Created by Open3D
element vertex 45896
property double x
property double y
property double z
property uchar red
property uchar green
property uchar blue
end_header


And here the header of a scan of FAUST which works.

ply
format binary_little_endian 1.0
element vertex 177638
property float x
property float y
property float z
element face 354750
property list uchar int vertex_indices
end_header

**Comment by sergeyprokudin** [comment]
I've made some changes, can you try now?

This is of course some ad hoc solution, I'll need to check the documentation for *.ply format to see the proper way of handling potential headers and color definitions.

**Comment by issibi** [comment]
no change, same error. i also can try to change the point cloud if i know how to prepare it. what is the problem ? missing faces ?

**Comment by sergeyprokudin** [comment]
Hm, this is strange. Are you sure you pulled the latest changes?

The problem is that your **scan_xyz** and **scan_rgb** arrays are of different shapes and cannot be concatenated. You can try replacing lines 80-85 with simply defining constant color RGB array:

```
scan_rgb = np.tile(np.asarray([0, 1.0, 0.5]), [n_scan_points, 1])
```

If this doesn't work as well, I would need some minimal failure case input to reproduce this behaviour.

**Comment by issibi** [comment]
Sorry! The filetime changed but something went wrong with pulling.

Checked again and It works now!!

:thumbsup:

Thnx a lot
